#!/usr/bin/env python3
"""Record a complete N1 exchange and explain its envelope and field records."""
import argparse
import io
from pathlib import Path
import socket
import client
from lab import LocalServer
import wire


def breakdown(packet):
    """Label every envelope and header-record byte group with its frame offset."""
    raw = packet.pack()
    rows = [(0, 2, 'signature "N1"'), (2, 1, 'type %s' % wire.LABELS.get(packet.kind, 'UNKNOWN')),
            (3, 1, 'flags' + (' FINISHED' if packet.flags & wire.FINISHED else ' none')),
            (4, 4, 'request id %d' % packet.request), (8, 4, 'payload length %d' % len(packet.body))]
    if packet.kind in (wire.REQUEST, wire.RESPONSE):
        at = wire.ENVELOPE.size
        def u16(offset):
            return int.from_bytes(raw[offset:offset + 2], 'big')
        count = u16(at)
        rows.append((at, 2, 'record count %d' % count))
        at += 2
        for _ in range(count):
            code = raw[at]
            if code:
                name = wire.NAMES[code - 1]
                rows.append((at, 1, 'name code %02x = %s' % (code, name)))
                at += 1
            else:
                size = u16(at + 1)
                name = raw[at + 3:at + 3 + size].decode('ascii')
                rows.append((at, 1, 'literal name follows'))
                rows.append((at + 1, 2, 'name length %d' % size))
                rows.append((at + 3, size, 'name "%s"' % name))
                at += 3 + size
            size = u16(at)
            rows.append((at, 2, 'value length %d' % size))
            value = raw[at + 2:at + 2 + size].decode('utf-8', 'backslashreplace')
            rows.append((at + 2, size, '%s value "%s"' % (name, value)))
            at += 2 + size
    elif packet.body:
        rows.append((wire.ENVELOPE.size, len(packet.body), 'file bytes, unchanged'))
    lines = ['| Offset | Bytes | Meaning |', '|---:|---|---|']
    for offset, size, meaning in rows:
        part = raw[offset:offset + size]
        shown = part.hex(' ') if size <= 8 else part[:6].hex(' ') + ' ... (%d bytes)' % size
        lines.append('| `%04x` | `%s` | %s |' % (offset, shown, meaning.replace('|', '\\|')))
    return lines


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--local', action='store_true', help='use a separate server process over a socket pair')
    parser.add_argument('--host', default='localhost')
    parser.add_argument('--port', type=int, default=9000)
    parser.add_argument('--path', default='/index.html')
    parser.add_argument('--output', type=Path, default=Path('docs/exchange.md'))
    args = parser.parse_args()
    packets = []
    def record(direction, packet):
        packets.append((direction, packet))
    sink = io.BytesIO()
    if args.local:
        with LocalServer(Path(__file__).resolve().parent / 'www') as app:
            status, _ = client.Fetcher(app.clients[0], 'local:9000', record).fetch(args.path, sink)
        transport = 'local stream socket pair, with the production server in a separate process'
    else:
        with socket.create_connection((args.host, args.port), 5) as sock:
            status, _ = client.Fetcher(sock, '%s:%d' % (args.host, args.port), record).fetch(args.path, sink)
        transport = 'TCP'
    lines = ['# N1: one exchange, every byte', '',
             'Capture transport: %s. Generated by `capture.py`; no bytes are omitted.' % transport,
             '', 'Request: `%s`; status: **%d**; file body: **%d bytes**.' %
             (args.path, status, len(sink.getvalue())), '',
             'Envelope offsets are fixed: `0..1 signature`, `2 type`, `3 flags`,',
             '`4..7 request id`, `8..11 payload length`. All integers are big-endian.', '']
    counts = {'TX': 0, 'RX': 0}
    for i, (direction, packet) in enumerate(packets, 1):
        counts[direction] += len(packet.pack())
        lines += ['## %d. %s %s' % (i, direction, wire.LABELS.get(packet.kind, 'UNKNOWN')),
                  '', '```text', wire.describe(packet), '```', '']
        lines += breakdown(packet) + ['']
        if packet.kind in (wire.REQUEST, wire.RESPONSE):
            lines += ['An indexed record is a name code, a u16 value length and the value. A literal '
                      'record is `00`, a u16 name length, the ASCII name, then the same value encoding.', '']
        elif packet.kind == wire.CONTENT:
            lines += [('FINISHED is set: this empty frame ends the response while the connection stays open.'
                       if packet.flags & wire.FINISHED else
                       'These payload bytes are file data. FINISHED is clear, so another frame follows.'), '']
    lines += ['Client sent **%d bytes**; server sent **%d bytes**. There is no connection preface.' %
              (counts['TX'], counts['RX']), '']
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(lines))
    print('Captured %d frames to %s' % (len(packets), args.output))


if __name__ == '__main__':
    main()
